### ISSUE TITLE
root : MainThread : INFO : setup returned 3 on "docker-inside-setup --auto-pull"

### ISSUE THREAD

**Issue by rrebollo** [boon-code/docker-inside#16]
First give me this:

DockerInside.Setup : MainThread : WARNING : Image 'alpine:3.6' not found locally -> pull it
root : MainThread : INFO : setup returned 3

Then i pulled 'alpine:3.6' with docker pull ...

Now i execute docker-inside-setup --auto-pull, it seems to be doing something for a while and at the end just throw me:

root : MainThread : INFO : setup returned 3

Am behind a corporate proxy, environment http_proxy and https_proxy vars are settle. Any clue here???

**Comment by boon-code** [comment]
You can try running this step using --verbose to maybe see the problem (and post the output here)
http_proxy and https_proxy will most certainly not be passed down to the container trying to clone & compile su-exec, so it seems plausible that this causes the issue.
I wouldn't see a huge problem in passing them to the container running the compilation, though...

**Comment by rrebollo** [comment]
Using --verbose i can confirm, could you adapt the setup script to work with env vars???

**Comment by boon-code** [comment]
I added a default list of environment variable that are used for proxy settings.
HTTP_PROXY and HTTPS_PROXY seem to work with apk. I didn't try Git...
Can you maybe try to install 0.3.15.X from https://test.pypi.org/project/docker-inside/ and let me know if this works for you?

**Comment by rrebollo** [comment]
Here is what i did:

export https_proxy="http://localhost:3128"

export http_proxy="http://localhost:3128"

pip3 install -i https://test.pypi.org/simple/ docker-inside

Output:
Looking in indexes: https://test.pypi.org/simple/
Collecting docker-inside  
  Downloading https://test-files.pythonhosted.org/packages/f7/38/8ca20a552309b6336538441341aeddf121e830b3687cfd0ee358e0cd39bf/docker-inside-0.3.15.101.tar.gz
Requirement already satisfied: argcomplete>=1.4.1 in /home/roly/.local/lib/python3.7/site-packages (from docker-inside) (1.12.1)
Requirement already satisfied: argparse>=1.4.0 in /home/roly/.local/lib/python3.7/site-packages (from docker-inside) (1.4.0)
Requirement already satisfied: docker>=2.7.0 in /home/roly/.local/lib/python3.7/site-packages (from docker-inside) (4.3.1)
Requirement already satisfied: dockerpty>=0.4.1 in /home/roly/.local/lib/python3.7/site-packages (from docker-inside) (0.4.1)
Requirement already satisfied: importlib-metadata<3,>=0.23; python_version == "3.7" in /home/roly/.local/lib/python3.7/site-packages (from argcomplete>=1.4.1->docker-inside) (2.0.0)
Requirement already satisfied: websocket-client>=0.32.0 in /home/roly/.local/lib/python3.7/site-packages (from docker>=2.7.0->docker-inside) (0.57.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/lib/python3/dist-packages (from docker>=2.7.0->docker-inside) (2.21.0)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from docker>=2.7.0->docker-inside) (1.12.0)
Requirement already satisfied: zipp>=0.5 in /home/roly/.local/lib/python3.7/site-packages (from importlib-metadata<3,>=0.23; python_version == "3.7"->argcomplete>=1.4.1->docker-inside) (3.3.1)
Building wheels for collected packages: docker-inside
  Running setup.py bdist_wheel for docker-inside ... done
  Stored in directory: /home/roly/.cache/pip/wheels/0a/32/a2/03fa1adf511b137d6dafd141c60e367a5dbf00b6ae292f10d6
Successfully built docker-inside
Installing collected packages: docker-inside
Successfully installed docker-inside-0.3.15

docker-inside-setup --verbose --auto-pull

Output:
docker-inside-setup --verbose --auto-pull
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "GET /v1.40/images/alpine:3.6/json HTTP/1.1" 404 67
DockerInside.Setup : MainThread : WARNING : Image 'alpine:3.6' not found locally -> pull it
docker.auth : MainThread : DEBUG : Looking for auth config
docker.auth : MainThread : DEBUG : Looking for auth entry for 'docker.io'
docker.auth : MainThread : DEBUG : No entry found
docker.auth : MainThread : DEBUG : No auth config found
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/images/create?tag=3.6&fromImage=alpine HTTP/1.1" 500 157
root : MainThread : ERROR : Failed to run setup()
Traceback (most recent call last):
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/alpine:3.6/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roly/.local/lib/python3.7/site-packages/dockerinside/dockerutils.py", line 245, in _assert_image_available
    self._dc.images.get(image_spec)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/roly/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/image.py", line 246, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: alpine:3.6: No such image: alpine:3.6")
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/images/create?tag=3.6&fromImage=alpine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roly/.local/lib/python3.7/site-packages/dockerinside/setup/__init__.py", line 138, in run
    refspec=self._args.refspec)
  File "/home/roly/.local/lib/python3.7/site-packages/dockerinside/setup/__init__.py", line 83, in setup
    self._assert_image_available(self.DEFAULT_IMAGE, auto_pull)
  File "/home/roly/.local/lib/python3.7/site-packages/dockerinside/dockerutils.py", line 250, in _assert_image_available
    self._dc.images.pull(img, tag)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/models/images.py", line 445, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/roly/.local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")

Making a curl -vvvvvv https://registry-1.docker.io/v2/ from the same terminal, i got:

* Expire in 0 ms for 6 (transfer 0x55b22c5dce80)
* Uses proxy env variable https_proxy == 'http://localhost:3128'
* Expire in 1 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 1 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 1 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 1 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 1 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 1 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
* Expire in 0 ms for 1 (transfer 0x55b22c5dce80)
.............................................................................
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x55b22c5dce80)
* Expire in 200 ms for 4 (transfer 0x55b22c5dce80)
* connect to ::1 port 3128 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x55b22c5dce80)
* Connected to localhost (127.0.0.1) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to registry-1.docker.io:443
> CONNECT registry-1.docker.io:443 HTTP/1.1
> Host: registry-1.docker.io:443
> User-Agent: curl/7.64.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Connection: close
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.docker.io
*  start date: May 23 00:00:00 2020 GMT
*  expire date: Jun 23 12:00:00 2021 GMT
*  subjectAltName: host "registry-1.docker.io" matched cert's "*.docker.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /v2/ HTTP/1.1
> Host: registry-1.docker.io
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Docker-Distribution-Api-Version: registry/2.0
< Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
< Date: Wed, 21 Oct 2020 17:04:04 GMT
< Content-Length: 87
< Strict-Transport-Security: max-age=31536000
<
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
* Connection #0 to host localhost left intact

**Comment by boon-code** [comment]
Can you try HTTP_PROXY and HTTPS_PROXY (all caps)?

**Comment by rrebollo** [comment]
This is the output with env vars on all caps
```
docker-inside-setup --verbose --auto-pull
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "GET /v1.40/images/alpine:3.6/json HTTP/1.1" 404 67
DockerInside.Setup : MainThread : WARNING : Image 'alpine:3.6' not found locally -> pull it
docker.auth : MainThread : DEBUG : Looking for auth config
docker.auth : MainThread : DEBUG : Looking for auth entry for 'docker.io'
docker.auth : MainThread : DEBUG : No entry found
docker.auth : MainThread : DEBUG : No auth config found
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/images/create?tag=3.6&fromImage=alpine HTTP/1.1" 200 None
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "GET /v1.40/images/alpine:3.6/json HTTP/1.1" 200 1918
DockerInside.Setup : MainThread : DEBUG : Configuration directory (host): /home/roly/.config/docker_inside
root : MainThread : DEBUG : Directory '/home/roly/.config/docker_inside' already exists
root : MainThread : DEBUG : Prepared environment: {'HTTPS_PROXY': 'http://localhost:3128', 'HTTP_PROXY': 'http://localhost:3128'}
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/containers/create HTTP/1.1" 201 88
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "GET /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/json HTTP/1.1" 200 None
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "PUT /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/archive?path=%2F HTTP/1.1" 200 0
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/start HTTP/1.1" 204 0
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "GET /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/logs?stderr=1&stdout=1&timestamps=0&follow=1&tail=all HTTP/1.1" 200 None
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "GET /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/json HTTP/1.1" 200 None
root : MainThread : DEBUG : fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
root : MainThread : DEBUG : WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz: network error (check Internet connection and firewall)
root : MainThread : DEBUG : fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
root : MainThread : DEBUG : WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz: network error (check Internet connection and firewall)
root : MainThread : DEBUG : ERROR: unsatisfiable constraints:
root : MainThread : DEBUG :   gcc (missing):
root : MainThread : DEBUG :     required by: world[gcc]
root : MainThread : DEBUG :   git (missing):
root : MainThread : DEBUG :     required by: world[git]
root : MainThread : DEBUG :   musl-dev (missing):
root : MainThread : DEBUG :     required by: world[musl-dev]
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/wait HTTP/1.1" 200 None
root : MainThread : INFO : setup returned 3
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/stop HTTP/11" 200 None
root : MainThread : INFO : setup returned 3
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "POST /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20/stop HTTP/1.1" 304 0
urllib3.connectionpool : MainThread : DEBUG : http://localhost:None "DELETE /v1.40/containers/a342ce5d1b1b54012925c167029ed48371a5b29a7d6db2bdb6b0bf412b93df20?v=False&link=False&force=False HTTP/1.1" 204 0
```

**Comment by boon-code** [comment]
Ah, sorry, no that will not work. Your proxy is only running on localhost and docker will isolate access to localhost. I will check, it should be easy and not a huge problem to use the host network (similar to ``docker run ... --network host ...``). Maybe with an additional flag?

If your proxy server would run on a different host (f.e. on the your cooperate intranet), I would expect it to work the way you invoked it already...

**Comment by boon-code** [comment]
Okay, I added a `--host-network` flag, this should work for you...

- You have to set the variables -> `http_proxy`, `https_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` (maybe only the caps version is also enough...)
- you have to run it like this: `docker-inside-setup --verbose --auto-pull --host-network`
